## Answer 1

In [1]:
import numpy as np
x = np.array([2,3,4,1])
n = 6

np.vander(x,n)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [2]:
np.vander(x,n,increasing=False)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [3]:
np.vander(x,n,increasing=True)

array([[   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    1,    1,    1,    1,    1]])

In [4]:
np.vander(x,increasing=False)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])

## Answer 2

In [7]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def find_moving_average(values,window):
    weights = np.repeat(1.0,window)/window
    smas = np.convolve(values,weights,'valid')
    return smas 


find_moving_average(dataset,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])